# fly.toml app configuration file generated for teste-prisma1 on 2024-07-24T13:57:39-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'teste-prisma1'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[deploy.commands]]
  name = "Prisma Migrate"
  command = "npx prisma migrate dev --name init"

[[deploy.commands]]
  name = "Seed Data"
  command = "node seed.js"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
